apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agents.pipelinex.com
spec:
  group: pipelinex.com
  names:
    kind: Agent
    listKind: AgentList
    plural: agents
    singular: agent
  scope: Namespaced  # 或者改成 ClusterScoped，根据你的需求
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              liveTime:
                type: integer
                default: 1800
              podSpec:
                $ref: "#/definitions/io.k8s.api.core.v1.PodSpec"
            required:
            - liveTime
        required:
        - spec

