apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agents.pipelinex.com
spec:
  group: pipelinex.com
  names:
    kind: Agent
    listKind: AgentList
    plural: agents
    singular: agent
  scope: Namespaced  # 或者改成 ClusterScoped，根据你的需求
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            $ref: "#/definitions/v1.ObjectMeta"
          spec:
            type: object
            properties:
              liveTime:
                type: integer
            required:
            - liveTime
          status:
            type: object
            properties:
              pipelines:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    pod:
                      type: string
                    status:
                      type: string
        required:
        - spec
        - status

